highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: :title.html
paginate: 5
gems: [jekyll-paginate]
port: 4000
safe: true
url: http://biomadeira.github.io/vitae
author: Fábio Madeira

# edit this section with your information
# biomadeira.github.io - all contents run on /vitae/
# for a normal use at the base of the server change it to "/"
baseurl: /vitae/
title: Prawal Gangwar's Resume
name: Prawal Gangwar
email: prawal.gangwar@gmail.com 
email_full: mailto:prawal.gangwar@gmail.com
website: prawalgangwar.github.io
website_full: https://prawalgangwar.github.io
github: prawalgangwar
twitter: prawalgangwar
linkedin: prawalgangwar
tel: +91 9044340199

collections:
- employement
- project

# google_maps: 'https://www.google.co.uk/maps/place/44+Perth+St,+Edinburgh,+Edinburgh+City+EH3+5BL'
address: Texas Instruments
city: Bengaluru
country: India
google_analytics: UA-101400553-1

# needed for travis-ci build
exclude: [vendor]
